[package]
name = "logic-form"
version = "0.2.1"
license = "MIT"
description = "Rust library for representing Cube, Clause, CNF and DNF"
edition = "2021"
repository = "https://github.com/gipsyh/logic-form"
authors = ["Yuheng Su <gipsyh.icu@gmail.com>"]
keywords = ["logic", "clause", "cube", "cnf", "dnf"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no_bound_check = []

[dependencies]
lazy_static = "1.4.0"
strum = { version = "0.26.2", features = ["derive"] }
giputils = { path = "../giputils", version = "0.2.0" }
ahash = "0.8.11"
